### ISSUE TITLE
config_check in v0.96 errors

### ISSUE THREAD

**Issue by bbrendon** [pnbruckner/ha-illuminance#1]
I poked around and tried a few things but wasn't able to figure this out. All of my other custom_components are fine. This started with the 96 upgrade.

```
Testing configuration at /opt/hass-prod-cfg
Failed config
  General Errors:
    - Platform not found: sensor.illuminance

Successful config (partial)
```

**Comment by bbrendon** [comment]
Tried fixing this an wasn't able to. This is what I have in my config.

```
sensor:
  - platform: illuminance
    name: outside_illuminance_est
    entity_id: weather.dark_sky
```
