### ISSUE TITLE
Feature Request: Brightness percentage entities

### ISSUE THREAD

**Issue by emansom** [pnbruckner/ha-illuminance#30]
It would be helpful if `ha-illuminance` provides entities to be used as value for the brightness of light entities.

Multiple entities for different needs:
- brightness percentage mapping to estimated illuminance `(lux / (DAYLIGHT_LUX / 100))`
- brightness percentage mapping to estimated illuminance that does the reverse of above

The reverse values for people that want their lights to blast on in the evening, instead of following the natural circadian rhythm.

Filtered with lower bound set to 1 and upper bound to 100.

`DAYLIGHT_LUX` being `400`, the lux value during sunrise or sunset.

**Comment by emansom** [comment]
Currently testing the first `indoor brightness mapping to estimated illuminance` entity formula with the following configuration:

`configuration.yaml`
```yaml
template:
  sensor:
    - name: "Calculated Light Brightness"
      unit_of_measurement: "Int"
      state: >-
        {%- set lux = states('sensor.estimated_illuminance') | int(default=0) -%}
        {%- set perc = (lux / (1000 / 100)) | int -%}
        {{ perc }}

sensor:
  - platform: filter
    name: "Filtered Light Brightness"
    entity_id: sensor.calculated_light_brightness
    filters:
    - filter: range
      lower_bound: 1
      upper_bound: 100
```

automation:

```yaml
alias: Lights based on Estimated Illuminance
description: ""
trigger:
  - platform: time_pattern
    minutes: /1
condition:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.estimated_illuminance
        below: 14000
action:
  - service: script.turn_on
    entity_id: script.control_light_with_lux
mode: single
```

script:

```yaml
alias: Control Light With Lux
sequence:
  - service: light.turn_on
    data:
      entity_id: light.all_lights
      transition: 5
    data_template:
      brightness_pct: "{{ states('sensor.filtered_light_brightness') }}"
mode: single
```

It provides a ramp down of the brightness, reflecting the estimated illuminance during dusk as intended.

![Schermafdruk van 2022-12-10 19-48-32](https://user-images.githubusercontent.com/981494/206870748-88f1f7da-97b0-4c87-bf4a-2c5995b541d7.png)
