### ISSUE TITLE
More sensors

### ISSUE THREAD

**Issue by FranMaverix** [pnbruckner/ha-illuminance#39]
It is possible to create more of one illuminance sensor?
I have tried to for comparison between Accuweather, AEMET (Spain) and others, but witout luck.

And another question. It's the same to use 'weather.accuweather' and 'sensor.accuweather_cloud_cover' as entity for illuminance sensor creation? Or the integration takes the cloud cover from  'weather.accuweather' directly?

Thanks!

**Comment by pnbruckner** [comment]
If I understand your question correctly, you can create as many sensors as you want. E.g.,
```yaml
sensor:
  - platform: illuminance
    name: Illuminance Sensor 1
    entity_id: weather.accuweather
  - platform: illuminance
    name: Illuminance Sensor 2
    entity_id: sensor.accuweather_cloud_cover
```
For cloud coverage, it only uses the state of the entity, and if that state can be interpreted as a number, then it assumes it is a cloud percentage, otherwise it assumes it's a condition (such as sunny, etc.)
